### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by dotlambda** [pydanny/cached-property#131]
I'm getting the following test failure on Python 3.7:
```
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-3.9.3, py-1.7.0, pluggy-0.8.0
rootdir: /build/source, inifile:
collected 30 items

tests/test_async_cached_property.py ...                                  [ 10%]
tests/test_cached_property.py ...............F........                   [ 90%]
tests/test_coroutine_cached_property.py ...                              [100%]

=================================== FAILURES ===================================
______________ TestCachedPropertyWithTTL.test_threads_ttl_expiry _______________

self = <tests.test_cached_property.TestCachedPropertyWithTTL testMethod=test_threads_ttl_expiry>

    def test_threads_ttl_expiry(self):
        Check = CheckFactory(self.cached_property_factory(ttl=100000), threadsafe=True)
        check = Check()
        num_threads = 5

        # Same as in test_threads
        check.run_threads(num_threads)
        self.assert_cached(check, num_threads)
        self.assert_cached(check, num_threads)

        # The cache expires in the future
        with freeze_time("9999-01-01"):
            check.run_threads(num_threads)
>           self.assert_cached(check, 2 * num_threads)

tests/test_cached_property.py:207:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_cached_property.py:69: in assert_cached
    self.assertEqual(check.add_cached, expected)
E   AssertionError: 6 != 10
===================== 1 failed, 29 passed in 8.39 seconds ======================
```
Do you have any idea why this could happen?

**Comment by dotlambda** [comment]
Seems like this is related to having freezegun-0.3.11: https://github.com/pydanny/cached-property/pull/125.

**Comment by althonos** [comment]
Otherwise, as a fudge, it's possible to create the context with a *really empty* `ignore` list through a little hack:
```python
with freeze_time("9999-01-01", ignore=nolist()):
    check.run_threads(num_threads)
    self.assert_cached(check, 2 * num_threads)
    self.assert_cached(check, 2 * num_threads)
```

with `nolist` defined as:
```python
class nolist(list):
    def append(self, item): pass
    def __getitem__(self, index): return self
```

**Comment by AdamWill** [comment]
Note for the record, if I'm following the maze of somewhat confusing issues related to this correctly, https://github.com/spulec/freezegun/commit/028dee229f06d200d0f79a130deaad65b14779ef is intended to fix it...See:

* https://github.com/spulec/freezegun/issues/269
* https://github.com/ktosiek/pytest-freezegun/issues/6

**Comment by AdamWill** [comment]
Well, nope, that doesn't fix it apparently. Sigh.

**Comment by AdamWill** [comment]
The fudge suggested by @althonos doesn't seem to help for me either :/

**Comment by shadchin** [comment]
For me work next patch
```python
        # The cache expires in the future
        import freezegun.api
        orig_value = freezegun.api.call_stack_inspection_limit
        freezegun.api.call_stack_inspection_limit = 0
        with freeze_time("9999-01-01"):
            check.run_threads(num_threads)
            self.assert_cached(check, 2 * num_threads)
            self.assert_cached(check, 2 * num_threads)
        freezegun.api.call_stack_inspection_limit = orig_value
```

**Comment by mbehrle** [comment]
> For me work next patch
> 
> ```python
>         # The cache expires in the future
>         import freezegun.api
>         orig_value = freezegun.api.call_stack_inspection_limit
>         freezegun.api.call_stack_inspection_limit = 0
>         with freeze_time("9999-01-01"):
>             check.run_threads(num_threads)
>             self.assert_cached(check, 2 * num_threads)
>             self.assert_cached(check, 2 * num_threads)
>         freezegun.api.call_stack_inspection_limit = orig_value
> ```

JFTR: Tested and didn't work for me:
FAIL: test_threads_ttl_expiry (tests.test_cached_property.TestCachedPropertyWithTTL)
----------------------------------------------------------------------
Traceback (most recent call last):                         
  File "/tmp/autopkgtest.UlW7E1/autopkgtest_tmp/tests/test_cached_property.py", line 207, in test_threads_ttl_expiry  
    self.assert_cached(check, 2 * num_threads)                                                                        
  File "/tmp/autopkgtest.UlW7E1/autopkgtest_tmp/tests/test_cached_property.py", line 69, in assert_cached             
    self.assertEqual(check.add_cached, expected)                                                                      
AssertionError: 6 != 10                                                                                               
                                                           
======================================================================
FAIL: test_threads_ttl_expiry (tests.test_cached_property.TestThreadedCachedPropertyWithTTL)
----------------------------------------------------------------------                                                
Traceback (most recent call last):                         
  File "/tmp/autopkgtest.UlW7E1/autopkgtest_tmp/tests/test_cached_property.py", line 238, in test_threads_ttl_expiry  
    self.assert_cached(check, 2 * num_threads)             
  File "/tmp/autopkgtest.UlW7E1/autopkgtest_tmp/tests/test_cached_property.py", line 69, in assert_cached             
    self.assertEqual(check.add_cached, expected)           
AssertionError: 2 != 10  

Both issues

    spulec/freezegun#269
    ktosiek/pytest-freezegun#6

are closed and I was testing with recent freezegun version 0.3.15.

I have also tested the patch by @althonos with no success.

Is there any way forward to get the test suite running completely again?

**Comment by FedericoCeratto** [comment]
Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923282

**Comment by AdamWill** [comment]
FWIW, I just did test Fedora builds of cached-property 2.0.1 with the patch to disable some assertions removed, and they worked fine, so this may no longer be an issue with recent cached-property and freezegun 1.5.1...
