### ISSUE TITLE
No compatible with `__slots__`

### ISSUE THREAD

**Issue by yahya-abou-imran** [pydanny/cached-property#69]
Hi. Very interresting project.
I was about to develop the same thing, but made a research first and found this

The problem is that it doesn't support the use of `__slots__`

Demonstration:
```python
>>> from cached_property import cached_property
>>> class C:
...     __slots__ = 'x',
...     @cached_property
...     def y(self):
...         return 'y'
... 
>>> c = C()
>>> c.y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
AttributeError: 'C' object has no attribute '__dict__'
```

I have a little wrapper for this named `slot_wrapper` [here:](https://github.com/yahya-abou-imran/metannotations/blob/9b6d9406817d64c36ff8e9911429c1dfc2f409cb/metannotations.py#L47)
```
def slot_wrapper(attrname, slot, Descr, cls):

    class InnerDescr(Descr):

        def __get__(self, obj, cls):
            return slot.__get__(obj, cls)

        def __set__(self, obj, val):
            slot.__set__(obj, val)

return InnerDescr(attrname, cls)
```
It takes the descriptor under the slot and replace it (__slots__ are special descriptors, but they remains descriptors).
It needs adjustments with your code in order to work... I use it with metclass so it got instaciate after the creation of the class.

My demand is between a bug report, a feature request and an enhacement proposal!

**Comment by Nath-P** [comment]
a workaround for this is to add    `__dict__`  to the the items slots. (got the idea to do this from https://docs.python.org/3/reference/datamodel.html#slots)

**Comment by althonos** [comment]
Or use [`property-cached`](https://pypi.org/project/property-cached) :wink:

**Comment by ZhymabekRoman** [comment]
Bump, same problem
